In [0]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn as sk
import catboost

In [0]:
data = pd.read_csv('drive/My Drive/Colab Notebooks/data_titanic/train.csv')
data.head()
data.shape

(891, 12)

In [0]:
for i in data.columns:
  print(i)

PassengerId
Survived
Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Cabin
Embarked


In [0]:
test_data = pd.read_csv('drive/My Drive/Colab Notebooks/data_titanic/test.csv')
test_data

PassengerId  Pclass  ... Cabin Embarked
0            892       3  ...   NaN        Q
1            893       3  ...   NaN        S
2            894       2  ...   NaN        Q
3            895       3  ...   NaN        S
4            896       3  ...   NaN        S
..           ...     ...  ...   ...      ...
413         1305       3  ...   NaN        S
414         1306       1  ...  C105        C
415         1307       3  ...   NaN        S
416         1308       3  ...   NaN        S
417         1309       3  ...   NaN        C

[418 rows x 11 columns]

In [0]:
X = data.drop('Survived', axis=1)
y = data['Survived']

In [0]:
X.head()
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

# **Обработка и очищение данных**

In [0]:
def num_sex(sex):
  if sex == 'male':
    return 1
  else:
    return 2

In [0]:
def data_preparation(raw_data):
  raw_data['Sex_num'] = raw_data['Sex'].apply(num_sex)
  if int(raw_data['Fare'].isnull().sum()) > 0:
    raw_data.Fare.fillna(raw_data.Fare.mean(), inplace=True)
  raw_data.Age.fillna(raw_data.Age.mean(), inplace=True)
  raw_data['Family'] = raw_data['SibSp'] + raw_data['Parch']
  raw_data_cat = pd.get_dummies(raw_data.Embarked)
  new_data = pd.concat([raw_data[['Pclass', 'Age', 'Family', 'Fare', 'Sex_num']], raw_data_cat], axis=1)
  return new_data

In [0]:
def data_preparation_full(raw_data):
  if int(raw_data['Fare'].isnull().sum()) > 0:
    raw_data.Fare.fillna(raw_data.Fare.mean(), inplace=True)
  if int(raw_data['Cabin'].isnull().sum()) > 0:
    raw_data.Cabin.fillna('-42', inplace=True)
  if int(raw_data['Embarked'].isnull().sum()) > 0:
    raw_data.Embarked.fillna('-42', inplace=True)
  raw_data.Age.fillna(raw_data.Age.mean(), inplace=True)
  return raw_data

In [0]:
prepared_train_data = data_preparation_full(X.copy())
prepared_train_data

PassengerId  Pclass  ... Cabin Embarked
0              1       3  ...   -42        S
1              2       1  ...   C85        C
2              3       3  ...   -42        S
3              4       1  ...  C123        S
4              5       3  ...   -42        S
..           ...     ...  ...   ...      ...
886          887       2  ...   -42        S
887          888       1  ...   B42        S
888          889       3  ...   -42        S
889          890       1  ...  C148        C
890          891       3  ...   -42        Q

[891 rows x 11 columns]

In [0]:
prepared_train_data.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [0]:
prepared_test_data = data_preparation_full(test_data.copy())
prepared_test_data

PassengerId  Pclass  ... Cabin Embarked
0            892       3  ...   -42        Q
1            893       3  ...   -42        S
2            894       2  ...   -42        Q
3            895       3  ...   -42        S
4            896       3  ...   -42        S
..           ...     ...  ...   ...      ...
413         1305       3  ...   -42        S
414         1306       1  ...  C105        C
415         1307       3  ...   -42        S
416         1308       3  ...   -42        S
417         1309       3  ...   -42        C

[418 rows x 11 columns]

In [0]:
prepared_test_data.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [0]:
categorical_features_indices = np.where(prepared_train_data.dtypes == object)[0]

In [0]:
categorical_features_indices

array([ 2,  3,  7,  9, 10])

In [0]:
prepared_train_data.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

# **Первая модель**

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [0]:
X_train, X_validation, y_train, y_validation = train_test_split(prepared_train_data, y, train_size=0.75, random_state=42)

In [0]:
model = catboost.CatBoostClassifier(
    custom_loss=['Accuracy'],
    random_seed=42,
    logging_level='Silent'
)

In [0]:
model.fit(
    X_train, y_train,
    cat_features=categorical_features_indices,
    eval_set=(X_validation, y_validation),
    # logging_level='Verbose',  # you can uncomment this for text output
    plot=True
);

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [0]:
cv_params = model.get_params()
cv_params.update({
    'loss_function': 'Logloss'
})
cv_data = catboost.cv(
    catboost.Pool(prepared_train_data, y, cat_features=categorical_features_indices),
    cv_params,
    plot=True
)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [0]:
print('Best validation accuracy score: {:.2f}±{:.2f} on step {}'.format(
    np.max(cv_data['test-Accuracy-mean']),
    cv_data['test-Accuracy-std'][np.argmax(cv_data['test-Accuracy-mean'])],
    np.argmax(cv_data['test-Accuracy-mean'])
))

Best validation accuracy score: 0.83±0.02 on step 109


/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:61: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  return bound(*args, **kwds)


In [0]:
print('Precise validation accuracy score: {}'.format(np.max(cv_data['test-Accuracy-mean'])))

Precise validation accuracy score: 0.8338945005611672


In [0]:
predictions = model.predict(prepared_test_data)
predictions_probs = model.predict_proba(prepared_test_data)
print(predictions[:10])
print(predictions_probs[:10])

[0 0 0 0 1 0 1 0 1 0]
[[0.90132028 0.09867972]
 [0.63168188 0.36831812]
 [0.9018529  0.0981471 ]
 [0.91060524 0.08939476]
 [0.36689132 0.63310868]
 [0.83578542 0.16421458]
 [0.40804673 0.59195327]
 [0.89010723 0.10989277]
 [0.33523409 0.66476591]
 [0.97081175 0.02918825]]


In [0]:
predictions

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [0]:
sub = pd.DataFrame({'PassengerId':test_data['PassengerId'], 'Survived':predictions.astype(int)})
sub.to_csv('titanic_sub.csv', index=False)

In [28]:
sub

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]